//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int ID { get; set; }
        public int Fk_Region { get; set; }
        public string Direction1 { get; set; }
        public string Direction2 { get; set; }
        public int CP { get; set; }
        public bool Status { get; set; }
    
        public virtual tblRegion tblRegion { get; set; }
    }
}
